### PR TITLE
New Earthfile instead of Dockerfile

### PR DESCRIPTION
**Pull request by Mobilpadde**
I've decided to put in the good ol' n2a image but it get's cached to make the deployments easier 🥲

Also a few changes in the makefile. I did keep the `docker_run` but renamed it to `debug`, yet I still have to understadn what it does 😖

### CODE REVIEW

**Comment by Mobilpadde** [comment]
Might have to change a few things, as I'm not sure how the deployment process is? As far as I remember you're using dokku, but no comments about it - at least I don't see any that is.

**Review by aalemayhu — CHANGES_REQUESTED** [review]
I am fine with adding the earthfile but we are going to remove the Dockerfile. Please revert that change. Otherwise I can't accept it as is. Thanks!

**Comment by Mobilpadde** [comment]
> I am fine with adding the earthfile but we are going to remove the Dockerfile. Please revert that change. Otherwise I can't accept it as is. Thanks!

It's back again! :+1:

**Review by aalemayhu — APPROVED** [review]
✅ LGTM, thanks!

**Pull request merged**
